/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancansu;

import javax.swing.JFrame;

/**
 *
 * @author Administrator
 */
public class frm_admin extends javax.swing.JFrame {

    /**
     * Creates new form frm_admin
     */
    public frm_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuAddBoMon = new javax.swing.JMenuItem();
        MenuAddLop = new javax.swing.JMenuItem();
        MenuAddCVHT = new javax.swing.JMenuItem();
        MenuAddSV = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuFillterBoMon = new javax.swing.JMenuItem();
        MenuFillterLop = new javax.swing.JMenuItem();
        MenuFillterCVHT = new javax.swing.JMenuItem();
        MenuFillterSV = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã lớp", "Tên ban cán sự", "Chức vụ", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("Thêm mới");

        MenuAddBoMon.setText("Bộ môn");
        MenuAddBoMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAddBoMonActionPerformed(evt);
            }
        });
        jMenu1.add(MenuAddBoMon);

        MenuAddLop.setText("Lớp");
        MenuAddLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAddLopActionPerformed(evt);
            }
        });
        jMenu1.add(MenuAddLop);

        MenuAddCVHT.setText("Cố vấn học tập");
        MenuAddCVHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAddCVHTActionPerformed(evt);
            }
        });
        jMenu1.add(MenuAddCVHT);

        MenuAddSV.setText("Sinh Viên");
        MenuAddSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAddSVActionPerformed(evt);
            }
        });
        jMenu1.add(MenuAddSV);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Lọc danh sách");

        MenuFillterBoMon.setText("Bộ môn");
        jMenu2.add(MenuFillterBoMon);

        MenuFillterLop.setText("Lớp");
        jMenu2.add(MenuFillterLop);

        MenuFillterCVHT.setText("Cố vấn học tập");
        jMenu2.add(MenuFillterCVHT);

        MenuFillterSV.setText("Sinh viên");
        jMenu2.add(MenuFillterSV);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Đổi mật khẩu");
        jMenuBar1.add(jMenu7);

        jMenu8.setText("Đăng xuất");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAddLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAddLopActionPerformed
        this.setVisible(true);
        new fmr_lop().setVisible(true);
        
    }//GEN-LAST:event_MenuAddLopActionPerformed

    private void MenuAddBoMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAddBoMonActionPerformed
        this.setVisible(true);
        new frm_bomon().setVisible(true);
    }//GEN-LAST:event_MenuAddBoMonActionPerformed

    private void MenuAddCVHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAddCVHTActionPerformed
        this.setVisible(true);
        new Frm_Covan().setVisible(true);
    }//GEN-LAST:event_MenuAddCVHTActionPerformed

    private void MenuAddSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAddSVActionPerformed
        this.setVisible(true);
        new frm_SinhVien().setVisible(true);
    }//GEN-LAST:event_MenuAddSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAddBoMon;
    private javax.swing.JMenuItem MenuAddCVHT;
    private javax.swing.JMenuItem MenuAddLop;
    private javax.swing.JMenuItem MenuAddSV;
    private javax.swing.JMenuItem MenuFillterBoMon;
    private javax.swing.JMenuItem MenuFillterCVHT;
    private javax.swing.JMenuItem MenuFillterLop;
    private javax.swing.JMenuItem MenuFillterSV;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
